### ISSUE TITLE
[Tarea] Archivo resnet50_embeddings.json corrupto

### ISSUE THREAD

**Issue by rhanuch** [PUC-RecSys-Class/RecSysPUC-2020#14]
Hola!
El archivo `.json` de `2gb` que nos entregaron aparentemente tiene un error (o está corrupto). A continuación dejo el `traceback` al tratar de correrlo

```python
Traceback (most recent call last):
  File "lector.py", line 4, in <module>
    data = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 23859 (char 23858)
```

Para que lo revisen y puedan subir el archivo corregido
Gracias! 😄

**Comment by mcartagenah** [comment]
Lo voy a revisar y aviso apenas lo tenga listo.

Saludos

**Comment by mcartagenah** [comment]
Se subió una actualización del enunciado, ahora deberían estar bien los embeddings.

Saludos

**Comment by rhanuch** [comment]
Gracias!
